// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from "prisma/config";

console.log("DB URL:", process.env.DATABASE_URL);

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL,
  },
});